// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from "@typebot.io/forge";
import { plivoBlock } from ".";
import { auth } from "./auth";

export const plivoBlockSchema = parseBlockSchema(plivoBlock);
export const plivoCredentialsSchema = parseBlockCredentials(
  plivoBlock.id,
  auth,
);
